theme: jekyll-theme-cayman
title: Squareford | Most Secured Cryptocurrrency Exchange with 100% Cold Wallets
description: Squareford is an upcoming Cryptocurrency Exchange from India with the most secured systems and 100% cold storage and wallets
